bitcoin-resources/bitcoin-resources.github.io

CHANGELOG.md, collections/_articles/bitcoin-cant-be-copied.md, collections/_articles/bitcoin-does-not-waste-energy.md, collections/_articles/bitcoin-doesnt-waste-electricity.md, collections/_articles/bitcoin-has-no-intrinsic-valueand-thats-great.md, collections/_articles/bitcoin-is-not-too-slow.md, collections/_articles/bitcoin-is-not-too-volatile.md, collections/_articles/blockchain-proofof-work-isa-decentralized-clock.md, collections/_articles/gradually-then-suddenly.md, collections/_articles/moneyblockchainsandsocialscalability.md, collections/_articles/nothingis-cheaperthan-proofof-work.md, collections/_articles/shelling-out-the-originsof-money.md, collections/_articles/the-anatomyof-proofof-work.md, collections/_articles/thereisno-bitcoin20.md, collections/_articles/workis-timeless-stakeis-not.md
- Gradually, Then Suddenly by Parker Lewis
- Bitcoin Does Not Waste Energy by Parker Lewis
- Bitcoin Can’t Be Copied by Parker Lewis
- Bitcoin Is Not Too Volatile by Parker Lewis
- Bitcoin Is Not Too Slow by Parker Lewis
=> Add articles by Parker Lewis

CHANGELOG.md, collections/_articles/a-cypherpunks-manifesto.md, collections/_articles/bitcoin-wikis-privacy-aritcle.md, collections/_articles/bitcoinand-privacy.md, collections/_articles/bitcoinisa-decentralized-organism.md, collections/_articles/bitcoinisa-social-creature.md, collections/_articles/digital-cash-privacy.md, collections/_articles/fa-qfor-hodl-privacy.md, collections/_articles/fa-qfor-samourai-wallets-whirlpool.md, collections/_articles/fa-qfor-wasabi-wallet.md, collections/_articles/how-privateis-bitcoin.md, collections/_articles/protect-your-privacy.md, collections/_articles/the-casefor-electronic-cash.md, collections/_articles/the-casefor-privacy.md, collections/_articles/the-crypto-anarchist-manifesto.md, collections/_articles/the-cyphernomicon.md, collections/_articles/we-must-protectour-abilityto-transact-privately-online.md, collections/_articles/why-bitcoin-mattersfor-freedom.md
- Add Digital Cash & Privacy by Hal Finney
- Add The Case for Privacy by David D. Friedman
- Add Why Bitcoin Matters for Freedom by Alex Gladstein
=> Add privacy articles by Hal Finney, David Friedman, Alex Gladstein

CHANGELOG.md, _includes/bibliography.md, collections/_episodes/BRF16.md, index.md
- Also add episode 16 with Yan Pritzker as a selected podcast episode
=> Add Bitcoin Rapid-Fire with John Vallis

CHANGELOG.md, _includes/bibliography.md, collections/_episodes/BRF21.md, collections/_episodes/TFTC107.md, collections/_episodes/TFTC99.md, index.md
- Add curation: WTF Happened in 1971
- Add podcast episode: TFTC 107 with American Hodl
- Add podcast episode: Bitcoin Rapid Fire 21 with Vortex
- Add podcast episode: TFTC 99 with Raoul Pal
=> Add "WTF Happened in 1971" and some selected podcast episodes

collections/_books/antifragile.md, collections/_books/the-bed-of-procrustes.md
=> Fix subtitle mixup of Taleb's books

collections/_books/money-sound-and-unsound.md
=> Fix broken link of Salerno's Money: Sound and Unsound

collections/_episodes/SLP115.md
=> Add SLP151 to episode collection

_includes/bibliography.md, index.md
=> Add Crypto Words

CHANGELOG.md, collections/_articles/bitcoin-cannot-be-banned.md, collections/_articles/bitcoin-fixes-this.md, collections/_articles/bitcoin-is-not-backed-by-nothing.md, collections/_articles/bitcoin-is-not-for-criminals.md, collections/_articles/bitcoin-is-nota-pyramid-scheme.md, collections/_articles/bitcoin-isa-rally-cry.md, collections/_articles/bitcoin-not-blockchain.md, collections/_articles/bitcoin-obsoletes-all-other-money.md, collections/_articles/enders-game.md, collections/_books/free-software-free-society.md, collections/_books/the-cathedral-and-the-bazaar.md
* Bitcoin cannot be banned
* Bitcoin fixes this
* Bitcoin is not backed by nothing
* Bitcoin is not for criminals
* Bitcoin is not a pyramid scheme
* Bitcoin is a rally cry
* Bitcoin not blockchain
* Bitcoin obsoletes all other money
* Enders game
=> Add articles from Parker Lewis' Gradually, Then Suddenly series

CHANGELOG.md, _includes/bibliography.md, index.md
- Beginner's Guide to Bitcoin by Peter McCormack
- Bitcoin Matters by Beautyon
=> Add Noteworthy Podcast Series

CHANGELOG.md, collections/_articles/mastersand-slavesof-money.md, collections/_podcasts/OTB.md, collections/_podcasts/TCP.md
Added:
- Masters and Slaves of Money by Robert Breedlove
- The Chaincode Podcast by Chaincode Labs
=> Update Resources (2020-07-14)

index.md, podcasts.md
Moved
* selected podcast episodes
* noteworthy podcast series
to `/podcasts`.
=> refactor: move everything to do with podcasts to /podcasts

_includes/tagmoji.html, _includes/tags.html
More specialized pods incoming - this prepares the emojitags for the next update.
=> feat(tags): add qa 🙋 and design 🎨

_includes/curations.html, collections/_curations/awesome-bitcoinlistoflibrariesand-ap-is.md, collections/_curations/awesome-whatis-bitcoin-list.md, collections/_curations/bestof-bitcoin-magazine.md, collections/_curations/bitcoin-archive.md, collections/_curations/bitcoin-developer-guide.md, collections/_curations/bitcoin-explained.md, collections/_curations/bitcoin-information-resources.md, collections/_curations/bitcoin-learning-center.md, collections/_curations/bitcoin-learning-master-list.md, collections/_curations/bitcoin-literature.md, collections/_curations/bitcoin-node-guide.md, collections/_curations/bitcoin-only-learning-resources.md, collections/_curations/bitcoin-privacy-guide.md, collections/_curations/bitcoin-qa.md, collections/_curations/bitcoin-rabbit-hole.md, collections/_curations/bitcoin-survivors-book-list.md, collections/_curations/bitcoin-wiki.md, collections/_curations/curated-bitcoin-articles.md, collections/_curations/featured-episodesofthe-cryptoconomy-podcast.md, collections/_curations/learn-me-a-bitcoin.md, collections/_curations/libbitcoin-wiki.md, collections/_curations/mises-library.md, collections/_curations/multisig-guide.md, collections/_curations/no-ky-conly.md, collections/_curations/unenumerated.md, collections/_curations/words-amonthly-bitcoinjournal.md, collections/_curations/wtf-happened-in1971.md, index.md, scripts/spreadsheet_to_resource_mds/update_curations.py
* move guides to separate section
* introduce [Learning Sites](https://bitcoin-resources.com/#learning-sites) section
Content updates:
* add River Learn
* add Learn Me A Bitcoin
=> feat(curations): add guides and learning resources

_includes/navigation.html, books.md, collections/_curations/bitcoin-developer-guide.md, collections/_curations/bitcoin-explained.md, collections/_curations/bitcoin-learning-center.md, collections/_curations/bitcoin-node-guide.md, collections/_curations/bitcoin-privacy-guide.md, collections/_curations/bitcoin-qa.md, collections/_curations/bitcoin-wiki.md, collections/_curations/bitcoiner-guide.md, collections/_curations/learn-me-a-bitcoin.md, collections/_curations/libbitcoin-wiki.md, collections/_curations/lightning-node-management-guide.md, collections/_curations/multisig-guide.md, collections/_curations/no-ky-conly.md, index.md, podcasts.md
* separate `/books` page
* no change in content, i.e. no new books added as of now
=> feat(books): add dedicated books page

_includes/navigation.html
Add navigation link to videos section.
=> feat(nav): add videos

videos.md
=> feat(videos): Add The Beauty of Bitcoin

articles.md, collections/_articles/hyperbitcoinization-winner-takes-all.md, collections/_articles/hyperbitcoinization.md, collections/_articles/speculative-attack.md, collections/_articles/you-are-not-prepared.md
=> feat(articles): add hyperbitcoinization section

.gitignore, scripts/archive_links_from_spreadsheet/archive_article_links.py, scripts/archive_links_from_spreadsheet/grab_article_links.py
adding two scripts that 
1. will grab the orignal links from the articles in the spreadsheet and 
2. will run through all the links, that aren't archived yet and archive them via archive.is semi-automatically
=> add: scripts to grab and archive links from spreadsheet

.gitignore, scripts/archive_links_from_spreadsheet/archive_article_links.py, scripts/archive_links_from_spreadsheet/grab_article_links.py
=> feat(scripts): archive links

collections/_articles/ifyourenot-breaking-rulesyoure-doingit-wrong.md, collections/_articles/intent-complexityandthe-governance-paradox.md, collections/_articles/who-dares-wins.md, collections/_articles/why-bit-torrent-mattered.md, collections/_series/bittorrent-lessons-for-crypto.md
- https://archive.ph/6wZnl
- https://archive.ph/xPh5Q
- https://archive.ph/hqTDo
- https://archive.ph/Ks0NA
=> feat(series): add 'BitTorrent Lessons' series

videos.md
=> feat(videos): add Mises' bitcoin video

videos.md
Resolves a bunch of [open video issues](https://github.com/bitcoin-resources/bitcoin-resources.github.io/issues?q=is%3Aissue+is%3Aopen+label%3Avideos).
=> feat(videos): revamp & update

_includes/navigation.html, forks.md, i18n.md
https://bitcoin-resources.com/forks
=> feat: i18n aka forks

faq.md
=> feat(faq): add Ponzi question

_includes/head.html
Long overdue. Let's hope this works!
=> fix(books): properly set og:image for books
